### PR TITLE
Added header hiding (and fixed turbolinks...)

### LINKED ISSUE #19: Hide header on scroll down on mobile
The content space on mobile is a little bit cramped. Especially with the MLH badge hanging over content. How about making it so the header hides on scroll down and reappears on scroll up?

### PR DESCRIPTION
**Pull request by snyderks**
Will resolve #19 
Added a class to animate the header to hidden
Added a listener that adds and removes the class on scroll
Fixed the fact that turbolinks wasn't sourced correctly and so wasn't loading... (like, how?)

### CODE REVIEW

**Comment by snyderks** [comment]
Ping: if anyone still wants to review this, go ahead, otherwise I'll probably be merging tomorrow

File: js/header.js [hunk 1]
```diff
@@ -7,17 +7,24 @@ function header() {
     el.className = el.className.replace(" " + className, "");
   }
 
+  var prev_frame_scroll_position = window.scrollY;
   var last_known_scroll_position = window.scrollY;
```
Comment (domfarolino) [inline js/header.js]: Is there a reason we snake_case these variables but camelCase others?

File: _scss/components/_header.scss [hunk 2]
```diff
@@ -9,15 +9,26 @@
...
+    -ms-transition: background-color, transform $header-bg-transition-time ease;
+    transition: background-color, transform $header-bg-transition-time ease;
+  }
+
+  &.header--hidden {
+    transform: translateY(-200px);
+    -webkit-transition: background-color,
+      transform $header-bg-transition-time ease;
+    -ms-transition: background-color, transform $header-bg-transition-time ease;
+    transition: background-color, transform $header-bg-transition-time ease;
```
Comment (domfarolino) [inline _scss/components/_header.scss]: A couple things here:

1.) I notice we're using `$header-bg-transition-time`, however this is also used to guide our `transform` operation (not just `background-color`), so I feel like it would be good if the name was a little more general, and inclusive to all that we do with it. Thoughts?

2.) Are all of these vendor prefixes necessary? Did some editor plugin add these? If possible (and if we don't consistently use prefixes throughout the rest of the codebase, I haven't investigated this...) I'd like to see this as streamlined as possible if that's doable.

File: js/header.js [hunk 3]
```diff
@@ -51,9 +58,39 @@ function header() {
...
+          !el.classList.contains("header--hidden")
+        ) {
+          navToggle.checked = false; // collapse the mobile navbar
+          addClassTo(el, "header--hidden");
+        } else if (prev_frame_scroll_position > last_known_scroll_position) {
+          removeClassFrom(el, "header--hidden");
+        }
+        window.setTimeout(function() {
+          header_animating = false;
+        }, 100);
```
Comment (domfarolino) [inline js/header.js]: This 100 is interesting to me, isn't the `$header-bg-transition-time` (sp?) `500ms`? Also to be honest, I'd rather see us react to a [`transitionend`](https://developer.mozilla.org/en-US/docs/Web/Events/transitionend) event on the header if possible, which could set the `header_animating` (`headerAnimating`?) variable instead of the `setTimeout`.

Comment (domfarolino) [reply js/header.js]: I think we're using another `setTimeout` for something similar when manipulating the `ticking` variable. I haven't looked at it closely, but if we could also benefit from the `transitionend` event, I'd be in favor of changing that in this PR too, though opening up a separate issue for it is fine also.

File: _scss/components/_header.scss (hunk 2 above)
Comment (snyderks) [reply _scss/components/_header.scss]: I missed that browsers don't need prefixes anymore. I'll remove them.

**Comment by snyderks** [comment]
Made changes to reflect review requests
